export const userList = [
  {
    firstName: "naji",
    middleName: "darwin",
    lastName: "N",
    gender: "male",
    phoneNumber: "203480934",
    email: "naji@gmail.com",
    contactModes: ["email", "phone"],
    maritalStatus: "single",
    immediateJoiner: "no",
    id: 1,
  },
  {
    firstName: "hadi",
    middleName: "ramish",
    lastName: "K",
    gender: "male",
    phoneNumber: "203480934",
    email: "hadi@gmail.com",
    contactModes: ["email", "phone"],
    maritalStatus: "married",
    immediateJoiner: "yes",
    id: 2,
  },
  {
    firstName: "hussain",
    middleName: "bih",
    lastName: "Y",
    gender: "female",
    phoneNumber: "203480934",
    email: "hussain@gmail.com",
    contactModes: ["email"],
    maritalStatus: "single",
    immediateJoiner: "no",
    id: 3,
  },
];
